"""Frozen CSV contract captured before adding Excel support.

Snapshots are checked in, never regenerated by these tests. Changes require
the user's approval, including changes to existing pandas header behavior.
"""
import json
from pathlib import Path
from unittest.mock import Mock
from uuid import UUID

import pytest
from fastapi.testclient import TestClient

from backend.app.config import Settings
from backend.app.main import create_app


SNAPSHOTS = Path(__file__).parent / "snapshots" / "csv_contract.json"
CSV = b"customer,joined_date,spend\nAda,2026-01-02,12.5\nLin,2026-02-03,20.0\n"
FIXED_ID = "0123456789abcdef0123456789abcdef"
PLANS = {
    "total_revenue": {"aggregations": [{"column": "revenue", "func": "sum", "alias": "total_revenue"}]},
    "top_products": {
        "group_by": ["product"],
        "aggregations": [{"column": "revenue", "func": "sum", "alias": "total_revenue"}],
        "sort_by": "total_revenue", "ascending": False, "limit": 3,
    },
    "march_by_day": {
        "filters": [
            {"column": "order_date", "op": ">=", "value": "2025-03-01"},
            {"column": "order_date", "op": "<", "value": "2025-04-01"},
        ],
        "group_by": [{"column": "order_date", "grain": "day"}],
        "aggregations": [{"column": "revenue", "func": "sum", "alias": "total_revenue"}],
        "limit": 3,
    },
}


def csv_client(llm=None):
    settings = Settings(
        gemini_api_key="fixture", gemini_backup_api_key="",
        csv_path=Path(__file__).parents[1] / "data" / "sales_data.csv",
        rate_limit_per_minute=100,
    )
    return TestClient(create_app(settings, llm_client=llm or Mock()))


def test_csv_upload_schema_rows_and_count(monkeypatch):
    monkeypatch.setattr("backend.app.datasets.uuid4", lambda: UUID(FIXED_ID))
    expected = json.loads(SNAPSHOTS.read_text(encoding="utf-8"))
    with csv_client() as client:
        uploaded = client.post("/api/datasets", params={"filename": " customers.csv "},
                               content=CSV, headers={"Content-Type": "text/csv"})
        assert uploaded.status_code == 201
        assert uploaded.json() == expected["upload"]
        schema = client.get("/api/schema", params={"dataset_id": FIXED_ID})
        assert schema.status_code == 200
        assert schema.json() == expected["schema"]
        rows = client.get(f"/api/datasets/{FIXED_ID}/rows", params={"offset": 0, "limit": 1})
        assert rows.status_code == 200
        assert rows.json() == expected["rows"]
        rest = client.get(f"/api/datasets/{FIXED_ID}/rows", params={"offset": 1, "limit": 1})
        assert rest.json()["rows"] == [{"customer": "Lin", "joined_date": "2026-02-03T00:00:00", "spend": 20.0}]
        assert rest.json()["row_count"] == 2
        assert rest.json()["has_more"] is False


@pytest.mark.parametrize("content,status,message", [
    (b"\xff\xfe", 422, "The CSV must use UTF-8 encoding."),
    (b"", 422, "The uploaded CSV is empty."),
    (b"\n", 422, "The file could not be parsed as CSV."),
    (b"x" * (10 * 1024 * 1024 + 1), 413, "The CSV exceeds the 10 MB upload limit."),
    (b" ,value\na,1\n", 422, "Column names must be non-empty and unique."),
    (b"name, name\na,1\n", 422, "Column names must be non-empty and unique."),
    ((",".join(f"c{i}" for i in range(101)) + "\n").encode(), 422, "The CSV exceeds the 100-column limit."),
    (b"value\n" + b"1\n" * 100001, 422, "The CSV exceeds the 100,000-row limit."),
], ids=["encoding", "empty", "no-header", "size", "blank-name", "trimmed-duplicate", "columns", "rows"])
def test_csv_errors(content, status, message):
    with csv_client() as client:
        response = client.post("/api/datasets?filename=bad.csv", content=content,
                               headers={"Content-Type": "text/csv"})
    assert response.status_code == status
    assert response.json() == {"error": message}


def test_csv_existing_header_and_extension_acceptance():
    with csv_client() as client:
        # pandas uses the first record as headers, even when it contains numbers.
        headerless = client.post("/api/datasets?filename=numbers.csv", content=b"1,2\n3,4\n")
        assert headerless.status_code == 201
        assert headerless.json()["column_names"] == ["1", "2"]
        assert headerless.json()["rows"] == [{"1": 3, "2": 4}]
        duplicate = client.post("/api/datasets?filename=duplicate.csv", content=b"name,name\na,b\n")
        assert duplicate.status_code == 201
        assert duplicate.json()["column_names"] == ["name", "name.1"]
        unnamed = client.post("/api/datasets?filename=unnamed.csv", content=b",value\na,1\n")
        assert unnamed.status_code == 201
        assert unnamed.json()["column_names"] == ["Unnamed: 0", "value"]
        # The existing API does not require a CSV extension or text/csv MIME type.
        arbitrary = client.post("/api/datasets?filename=data.txt", content=CSV,
                                headers={"Content-Type": "application/octet-stream"})
        assert arbitrary.status_code == 201
        assert arbitrary.json()["name"] == "data.txt"
        default_name = client.post("/api/datasets", content=b"\xef\xbb\xbfvalue\n1\n")
        assert default_name.status_code == 201
        assert default_name.json()["name"] == "Uploaded CSV"
        assert default_name.json()["rows"] == [{"value": 1}]
        assert "datasets" not in default_name.json()


def test_csv_preview_and_id_generation():
    with csv_client() as client:
        response = client.post("/api/datasets?filename=preview.csv", content=b"value\n" + b"1\n" * 23)
    assert response.status_code == 201
    body = response.json()
    assert UUID(hex=body["dataset_id"]).version == 4
    assert len(body["dataset_id"]) == 32
    assert len(body["rows"]) == 20
    assert body["row_count"] == 23
    assert set(body) == {"dataset_id", "name", "columns", "column_names", "rows", "row_count"}


@pytest.mark.parametrize("name", PLANS)
def test_csv_bundled_query_snapshots(name):
    llm = Mock()
    llm.generate.return_value = json.dumps(PLANS[name])
    expected = json.loads(SNAPSHOTS.read_text(encoding="utf-8"))["queries"][name]
    with csv_client(llm) as client:
        response = client.post("/api/query", json={"question": name, "dataset_id": "default"})
    assert response.status_code == 200
    assert response.json() == expected
    llm.generate.assert_called_once()
