from __future__ import annotations

from typing import Any

import pandas as pd


COLUMN_METADATA: dict[str, dict[str, Any]] = {
    "order_id": {"description": "Unique identifier of an order."},
    "order_date": {"description": "Date when the order was placed.", "synonyms": ["date", "purchase date", "sale date"]},
    "product": {"description": "Product purchased in the order.", "synonyms": ["item", "product name", "goods"]},
    "category": {"description": "Product category.", "synonyms": ["group", "product type"]},
    "region": {"description": "City where the order was placed.", "synonyms": ["city", "location", "province", "area"]},
    "quantity": {"description": "Number of units purchased.", "unit": "items", "synonyms": ["amount", "units", "items", "pieces"]},
    "unit_price": {"description": "Selling price of one product unit.", "unit": "USD", "synonyms": ["price", "cost", "price per unit"]},
    "revenue": {"description": "Total revenue generated by the order.", "unit": "USD", "synonyms": ["sales", "income", "earnings", "turnover"]},
}

BUSINESS_RULES = [
    "Each row is one record in the uploaded dataset.",
    "Use only facts, columns, types, and allowed values shown in the schema.",
    "Do not infer information that is not present in the dataset.",
]

EXAMPLE_QUESTIONS = [
    "Top 5 products by revenue",
    "Total revenue by region",
    "Average unit price of Electronics",
    "How many laptops were sold?",
    "Revenue in Hanoi during June",
    "What was revenue in March 2025?",
]


def build_schema(df: pd.DataFrame) -> list[dict[str, Any]]:
    schema: list[dict[str, Any]] = []
    for column in df.columns:
        metadata = COLUMN_METADATA.get(column, {})
        item: dict[str, Any] = {
            "name": str(column),
            "type": str(df[column].dtype),
            "description": metadata.get("description", "Dataset column."),
        }
        for key in ("unit", "synonyms"):
            if key in metadata:
                item[key] = metadata[key]
        if pd.api.types.is_string_dtype(df[column].dtype):
            values = sorted(str(value) for value in df[column].dropna().unique())
            if len(values) <= 50:
                item["allowed_values"] = values
        if pd.api.types.is_datetime64_any_dtype(df[column].dtype) and df[column].notna().any():
            item["min"] = pd.Timestamp(df[column].min()).isoformat()
            item["max"] = pd.Timestamp(df[column].max()).isoformat()
        schema.append(item)
    return schema


def example_questions(schema: list[dict[str, Any]]) -> list[str]:
    names = [item["name"] for item in schema]
    if set(COLUMN_METADATA).issubset(names):
        return EXAMPLE_QUESTIONS
    first = names[0]
    questions = [
        "Show the first 20 rows",
        f"How many unique values are in {first}?",
        f"Sort by {first}",
        f"Show records where {first} is not empty",
    ]
    if len(names) > 1:
        questions.extend([f"Group by {first} and count {names[1]}", f"Show only {first} and {names[1]}"])
    return questions[:6]


def validate_declared_columns(df: pd.DataFrame) -> None:
    unknown = set(COLUMN_METADATA) - set(df.columns)
    if unknown:
        raise RuntimeError(f"Schema metadata references missing columns: {sorted(unknown)}")
