from __future__ import annotations

from typing import Any

import pandas as pd


COLUMN_METADATA: dict[str, dict[str, Any]] = {
    "order_id": {"description": "Unique identifier of an order."},
    "order_date": {"description": "Date when the order was placed.", "synonyms": ["date", "purchase date", "sale date"]},
    "product": {"description": "Product purchased in the order.", "synonyms": ["item", "product name", "goods"]},
    "category": {"description": "Product category.", "synonyms": ["group", "product type"]},
    "region": {"description": "City where the order was placed.", "synonyms": ["city", "location", "province", "area"]},
    "quantity": {"description": "Number of units purchased.", "unit": "items", "synonyms": ["amount", "units", "items", "pieces"]},
    "unit_price": {"description": "Selling price of one product unit.", "unit": "USD", "synonyms": ["price", "cost", "price per unit"]},
    "revenue": {"description": "Total revenue generated by the order.", "unit": "USD", "synonyms": ["sales", "income", "earnings", "turnover"]},
}

BUSINESS_RULES = [
    "Each row represents one order.",
    "Revenue is already calculated for each order.",
    "All monetary values are in USD.",
    "Dates use YYYY-MM-DD.",
    "Do not infer information that is not present in the dataset.",
]

EXAMPLE_QUESTIONS = [
    "Top 5 products by revenue",
    "Total revenue by region",
    "Average unit price of Electronics",
    "How many laptops were sold?",
    "Revenue in Hanoi during June",
    "What was revenue in March 2025?",
]


def build_schema(df: pd.DataFrame) -> list[dict[str, Any]]:
    schema: list[dict[str, Any]] = []
    for column in df.columns:
        metadata = COLUMN_METADATA.get(column, {})
        item: dict[str, Any] = {
            "name": str(column),
            "type": str(df[column].dtype),
            "description": metadata.get("description", "Dataset column."),
        }
        for key in ("unit", "synonyms"):
            if key in metadata:
                item[key] = metadata[key]
        if pd.api.types.is_string_dtype(df[column].dtype):
            values = sorted(str(value) for value in df[column].dropna().unique())
            if len(values) <= 50:
                item["allowed_values"] = values
        schema.append(item)
    return schema


def validate_declared_columns(df: pd.DataFrame) -> None:
    unknown = set(COLUMN_METADATA) - set(df.columns)
    if unknown:
        raise RuntimeError(f"Schema metadata references missing columns: {sorted(unknown)}")

