"""
Schema metadata for the Sales Data demo.

This metadata is injected into the prompt so that the LLM
can better understand the dataset semantics.
"""

SCHEMA = [
    {
        "name": "order_id",
        "type": "string",
        "description": "Unique identifier of an order.",
        "examples": [
            "ORD00001",
            "ORD00521"
        ]
    },
    {
        "name": "order_date",
        "type": "date",
        "description": "Date when the order was placed.",
        "format": "YYYY-MM-DD",
        "synonyms": [
            "date",
            "purchase date",
            "sale date",
            "order time"
        ]
    },
    {
        "name": "product",
        "type": "string",
        "description": "Product purchased in the order.",
        "allowed_values": [
            "Laptop",
            "Monitor",
            "Tablet",
            "Smartphone",
            "Keyboard",
            "Mouse",
            "Headphones",
            "Webcam"
        ],
        "synonyms": [
            "item",
            "product name",
            "goods"
        ]
    },
    {
        "name": "category",
        "type": "string",
        "description": "Product category.",
        "allowed_values": [
            "Electronics",
            "Accessories"
        ],
        "synonyms": [
            "group",
            "product type"
        ]
    },
    {
        "name": "region",
        "type": "string",
        "description": "City where the order was placed.",
        "allowed_values": [
            "Hanoi",
            "Ho Chi Minh City",
            "Da Nang",
            "Hai Phong",
            "Can Tho"
        ],
        "synonyms": [
            "city",
            "location",
            "province",
            "area"
        ]
    },
    {
        "name": "quantity",
        "type": "integer",
        "description": "Number of units purchased.",
        "unit": "items",
        "synonyms": [
            "amount",
            "units",
            "items",
            "pieces",
            "sold quantity"
        ]
    },
    {
        "name": "unit_price",
        "type": "float",
        "description": "Selling price of a single product.",
        "unit": "USD",
        "synonyms": [
            "price",
            "cost",
            "price per unit"
        ]
    },
    {
        "name": "revenue",
        "type": "float",
        "description": "Total revenue generated by the order.",
        "unit": "USD",
        "formula": "quantity × unit_price × seasonal_multiplier",
        "synonyms": [
            "sales",
            "total sales",
            "income",
            "earnings",
            "turnover"
        ]
    }
]


BUSINESS_RULES = [
    "Each row represents one order.",
    "Revenue is already calculated for each order.",
    "Revenue = quantity × unit_price × seasonal_multiplier.",
    "Unit price is the selling price of one item.",
    "Quantity is the number of purchased items.",
    "All monetary values are in USD.",
    "Dates use the YYYY-MM-DD format.",
    "Category is determined by the product.",
    "Do not infer information that is not present in the dataset.",
    "Only use columns defined in the schema."
]


CLARIFICATION_RULES = [
    "If the user request is ambiguous, ask ONE clarification question before generating a query.",
    "Never guess the meaning of vague words such as 'best', 'highest', 'latest', 'top', 'popular', or 'recent'.",
    "When multiple metrics are possible, ask the user which metric they mean.",
    "When multiple date fields could apply, ask which date should be used.",
    "Never invent new columns.",
    "Never invent filter values.",
    "Only use values defined in the schema metadata whenever possible."
]


# Mỗi example giờ có "query" thật (đúng cú pháp pandas trên biến `df`)
# thay vì chỉ mô tả ý định bằng lời -> LLM học được cú pháp chính xác,
# giảm lỗi eval() và giảm ảo giác cột/hàm không tồn tại.
EXAMPLES = [
    {
        "question": "Top 5 products by revenue",
        "intent": "Sort revenue descending and return first 5 products.",
        "query": (
            "df.groupby('product')['revenue'].sum()"
            ".sort_values(ascending=False).head(5)"
        )
    },
    {
        "question": "Total revenue by region",
        "intent": "Group by region and aggregate revenue.",
        "query": "df.groupby('region')['revenue'].sum()"
    },
    {
        "question": "Average unit price of Electronics",
        "intent": "Filter category == Electronics then calculate average unit_price.",
        "query": "df[df['category'] == 'Electronics']['unit_price'].mean()"
    },
    {
        "question": "How many laptops were sold?",
        "intent": "Filter product == Laptop then sum quantity.",
        "query": "df[df['product'] == 'Laptop']['quantity'].sum()"
    },
    {
        "question": "Revenue in Hanoi during June",
        "intent": "Filter region and month, then aggregate revenue.",
        "query": (
            "df[(df['region'] == 'Hanoi') & (df['order_date'].dt.month == 6)]"
            "['revenue'].sum()"
        )
    },
    {
        "question": "What is the best product?",
        "intent": (
            "'Best' is ambiguous (could mean revenue, quantity sold, "
            "or number of orders) -> must ask for clarification instead "
            "of generating a query."
        ),
        "query": None
    }
]